Repository Arquisoft/dede_es3c, pull requests merged in 2022-05, with the labels that each got.

#320 Sergio
  .github/workflows/asw2122.yml
  .gitignore
  docker-compose-deploy.yml
  docker-compose.yml
  docs/04_solution_strategy.adoc
  docs/08_concepts.adoc
  docs/09_design_decisions.adoc
  docs/package-lock.json
  restapi/ormconfig.json
  restapi/package-lock.json
  restapi/package.json
  restapi/src/Api.ts
  restapi/src/controllers/Product_Controller.ts
  restapi/src/controllers/User_Controller.ts
  restapi/src/middlewares/Auth_Middleware.ts
  restapi/src/persistence/Database.ts
  restapi/tests/api.test.ts
  restapi/tests/jest.config.ts
  restapi/tests/tests_e2e.ts
  sonar-project.properties
  webapp/e2e/features/register-form.feature
  webapp/e2e/jest.config.ts
  webapp/e2e/steps/register-form.steps.ts
  webapp/package-lock.json
  webapp/package.json
  webapp/server.ts
  webapp/src/api/api.ts
  webapp/src/pages/LoginPage.tsx
  webapp/src/pages/SignUpPage.tsx
  webapp/tsconfig.json
Labels: BackEnd🧠

#329 Obtener precio de envío
  restapi/src/Api.ts
  restapi/src/controllers/Order_Controller.ts
Labels: BackEnd🧠

#334 Pequeños arreglos
  data/data.py
  restapi/src/Api.ts
  restapi/tests/api.test.ts
Labels: BackEnd🧠

#336 Building Blocks View - Level 2
  docs/05_building_block_view.adoc
  docs/08_concepts.adoc
  docs/11_technical_risks.adoc
  docs/12_glossary.adoc
  docs/images/05_2_Building_Block_View_Level_2.png
  docs/images/08_umldiagram.png
Labels: BackEnd🧠

#335 Sergio
  docs/09_design_decisions.adoc
  restapi/src/Api.ts
  webapp/e2e/features/register-form.feature
  webapp/e2e/steps/flow.steps.ts
  webapp/e2e/steps/logout-form.steps.ts
  webapp/e2e/steps/register-form.steps.ts
  webapp/src/pages/SignUpPage.tsx
Labels: BackEnd🧠

#340 Sonia docu4
  docs/images/03-Technical-Context.png
  webapp/src/api/api.ts
  webapp/src/langs/en.json
  webapp/src/langs/es.json
  webapp/src/pages/EditUserPage.tsx
  webapp/src/pages/ShippingPage.tsx
  webapp/src/pages/SignUpPage.tsx
Labels: documentation :page_facing_up:, FrontEnd👀

#345 CRUD de product store
  restapi/src/Api.ts
  restapi/src/controllers/ProductStore_Controller.ts
  restapi/src/controllers/Product_Controller.ts
  restapi/src/services/ProductStore_Service.ts
  restapi/src/services/Product_Service.ts
Labels: BackEnd🧠

#342 Sergio
  .github/workflows/asw2122.yml
  codecov.yml
  data/data.py
  docker-compose-deploy.yml
  docs/07_deployment_view.adoc
  docs/08_concepts.adoc
  docs/images/03-Business_Context.png
  docs/images/07-DiagramaDespliegue.png
  docs/images/07-Diagrama_de_despliege_T2.png
  restapi/src/Server.ts
  webapp/src/api/api.ts
Labels: documentation :page_facing_up:, BackEnd🧠

#338 Developer
  .github/workflows/asw2122.yml
  data/data.py
  docker-compose-deploy.yml
  docker-compose.yml
  docs/03_system_scope_and_context.adoc
  docs/06_runtime_view.adoc
  docs/07_deployment_view.adoc
  docs/08_concepts.adoc
  docs/images/03-Business_Context.png
  docs/images/03-Technical-Context.png
  docs/images/07-DiagramaDespliegue.png
  docs/images/07-Diagrama_de_despliege_T2.png
  docs/images/08_Homepage-final.PNG
  docs/images/08_Login-final.PNG
  restapi/src/Api.ts
  restapi/src/Server.ts
  restapi/src/controllers/ProductStore_Controller.ts
  restapi/src/controllers/Product_Controller.ts
  restapi/src/services/ProductStore_Service.ts
  restapi/src/services/Product_Service.ts
  webapp/src/App.tsx
  webapp/src/api/api.ts
  webapp/src/components/Cart.tsx
  webapp/src/components/Header.tsx
  webapp/src/langs/en.json
  webapp/src/langs/es.json
  webapp/src/pages/CrudAddPage.tsx
  webapp/src/pages/CrudDeletePage.tsx
  webapp/src/pages/CrudEditPage.tsx
  webapp/src/pages/EditUserPage.tsx
  webapp/src/pages/HomePage.tsx
  webapp/src/pages/LoginPage.tsx
  webapp/src/pages/OrdersPage.tsx
  webapp/src/pages/ShippingPage.tsx
  webapp/src/pages/SignUpPage.tsx
  webapp/src/test/ClientView.test.tsx
  webapp/src/test/CrudDeletePage.test.tsx
  webapp/src/test/EditUser.test.tsx
  webapp/src/test/SolidProvider.test.tsx
Labels: documentation :page_facing_up:

#348 Developer
  webapp/src/test/CrudUpdatePage.test.tsx
Labels: Testeo :lab_coat:

#351 Sergio
  webapp/src/api/api.ts
Labels: BackEnd🧠

#352 Developer
  README.md
  webapp/src/api/api.ts
Labels: BackEnd🧠

#356 Modificados punto 8.1 y 9
  docs/08_concepts.adoc
  docs/09_design_decisions.adoc
Labels: documentation :page_facing_up:

#353 Sergio
  .github/workflows/asw2122.yml
  codecov.yml
  docker-compose-deploy.yml
  docker-compose.yml
  restapi/data/.dockerignore
  restapi/data/Dockerfile
  restapi/data/README.md
  restapi/data/data.py
  restapi/data/requirements.txt
Labels: Testeo :lab_coat:

#357 Developer
  .github/workflows/asw2122.yml
  codecov.yml
  docker-compose-deploy.yml
  docker-compose.yml
  docs/08_concepts.adoc
  docs/09_design_decisions.adoc
  restapi/data/.dockerignore
  restapi/data/Dockerfile
  restapi/data/README.md
  restapi/data/data.py
  restapi/data/requirements.txt
  webapp/src/test/EditUser.test.tsx
Labels: documentation :page_facing_up:, Testeo :lab_coat:

#360 Sergio
  codecov.yml
  docker-compose-deploy.yml
  docker-compose.yml
Labels: BackEnd🧠

#362 Solucionado bug busqueda por texto vacía
  webapp/src/pages/Catalog.tsx
Labels: bug :ant:

#365 Fix data.py
  data/data.py
Labels: BackEnd🧠

#364 Tests de carga
  webapp/loadtest/GetProducts.scala
  webapp/loadtest/GetUsersList.scala
  webapp/loadtest/Login.scala
  webapp/loadtest/login/0001_request.txt
Labels: Testeo :lab_coat:

#367 Solucionados errores
  webapp/src/api/api.ts
  webapp/src/pages/AboutPage.tsx
  webapp/src/pages/CrudAddPage.tsx
Labels: FrontEnd👀

#368 Actualizado punto de Testability
  docs/08_concepts.adoc
  docs/images/08_Hexagonal.png
  docs/images/08_loadtests_getproducts15-30.png
  docs/images/08_loadtests_getproducts3-15.png
  docs/images/08_loadtests_getuserslist3-15.png
  docs/images/08_loadtests_login15-60.png
  docs/images/08_loadtests_login5000-60.png
Labels: documentation :page_facing_up:

#366 Sergio
  .github/workflows/asw2122.yml
  docs/08_concepts.adoc
  docs/09_design_decisions.adoc
  restapi/README.md
  webapp/e2e/features/flow.feature
  webapp/e2e/features/logout.feature
  webapp/e2e/jest.config.ts
  webapp/e2e/steps/flow.steps.ts
  webapp/e2e/steps/login-form.steps.ts
  webapp/e2e/steps/logout.steps.ts
  webapp/src/App.tsx
  webapp/src/api/api.ts
  webapp/src/components/DistributionCenterDisplay.tsx
  webapp/src/components/ItemDetails.tsx
  webapp/src/pages/EditUserPage.tsx
  webapp/src/pages/LoginPage.tsx
  webapp/src/pages/ShippingPage.tsx
Labels: BackEnd🧠

#375 Developer
  docs/01_introduction_and_goals.adoc
  docs/08_concepts.adoc
  docs/09_design_decisions.adoc
  docs/11_technical_risks.adoc
  webapp/package.json
Labels: BackEnd🧠

#376 hotfix
  data/data.py
Labels: BackEnd🧠

#377 Sergio
  .github/workflows/asw2122.yml
  README.md
  docker-compose-deploy.yml
Labels: BackEnd🧠

#380 Developer
  docker-compose-deploy.yml
Labels: BackEnd🧠
