Repository Arquisoft/dede_es3c, pull requests merged in 2022-04, with the labels that each got.

#230 Merge de pedidos y solid en developer
  .gitignore
  data/data.py
  docker-compose.yml
  docs/08_concepts.adoc
  docs/13_glossary.adoc
  docs/images/03-Technical-Context.png
  docs/images/08_dede_catalog.PNG
  docs/images/08_dede_login.PNG
  package-lock.json
  package.json
  restapi/package-lock.json
  restapi/package.json
  restapi/src/Api.ts
  restapi/src/controllers/Order_Controller.ts
  restapi/src/controllers/Product_Controller.ts
  restapi/src/controllers/User_Controller.ts
  restapi/src/entities/Order.ts
  restapi/src/entities/Product.ts
  restapi/src/entities/User.ts
  restapi/src/middlewares/Auth_Middleware.ts
  restapi/src/persistence/Database.ts
  restapi/src/services/Order_Service.ts
  restapi/src/services/Product_Service.ts
  restapi/tests/api.test.ts
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.test.tsx
  webapp/src/App.tsx
  webapp/src/api/api.ts
  webapp/src/components/Cart.tsx
  webapp/src/components/CartItem.tsx
  webapp/src/components/DisplayOrders.tsx
  webapp/src/components/Header.tsx
  webapp/src/components/Item.tsx
  webapp/src/img/checkout-icon.svg
  webapp/src/lang.tsx
  webapp/src/langs/en.json
  webapp/src/langs/es.json
  webapp/src/pages/Catalog.tsx
  webapp/src/pages/CatalogPage.tsx
  webapp/src/pages/CrudAddPage.tsx
  webapp/src/pages/CrudDeletePage.tsx
  webapp/src/pages/CrudEditPage.tsx
  webapp/src/pages/HomePage.tsx
  webapp/src/pages/LoginPage.tsx
  webapp/src/pages/OrdersPage.tsx
  webapp/src/pages/ShippingPage.tsx
  webapp/src/pages/SignUpPage.tsx
  webapp/src/shared/shareddtypes.ts
  webapp/src/test/HomePage.test.tsx
  webapp/src/test/OrderPage.test.tsx
Labels: FrontEnd👀, BackEnd🧠

#235 commit arreglando rutas
  webapp/src/langs/en.json
  webapp/src/pages/ShippingPage.tsx
Labels: FrontEnd👀

#229 Trabajo Sergio
  .github/workflows/asw2122.yml
  docker-compose.yml
  docs/04_solution_strategy.adoc
  docs/06_runtime_view.adoc
  docs/08_concepts.adoc
  docs/12_glossary.adoc
  docs/13_hexagonal_architecture.adoc
  docs/images/07-Diagrama de despliege-T2.png
  docs/images/07-DiagramaDespliegue.png
  docs/images/13_Hexagonal.png
  docs/images/Diagrama de despliege T2.png
  docs/images/logo-dede.PNG
  docs/images/logo-dede.png
  docs/package-lock.json
  package-lock.json
  package.json
  restapi/Dockerfile
  restapi/ormconfig.json
  restapi/package-lock.json
  restapi/package.json
  restapi/src/Api.ts
  restapi/src/controllers/Product_Controller.ts
  restapi/src/controllers/User_Controller.ts
  restapi/src/middlewares/Auth_Middleware.ts
  restapi/tests/api.test.ts
  webapp/Dockerfile
  webapp/src/App.test.tsx
Labels: Work :student:

#240 Documentación actualizada
  docs/08_concepts.adoc
  docs/13_hexagonal_architecture.adoc
  docs/images/logo-dede.png
  docs/index.adoc
  webapp/src/components/Header.tsx
  webapp/src/img/logo-dede.svg
Labels: documentation :page_facing_up:

#242 Developer
  docs/08_concepts.adoc
  docs/13_hexagonal_architecture.adoc
  docs/index.adoc
  webapp/src/pages/OrdersPage.tsx
  webapp/src/test/OrderPage.test.tsx
Labels: Work :student:

#272 Actualizando Developer tras los HotFix
  README.md
  docs/07_deployment_view.adoc
  docs/11_technical_risks.adoc
  docs/images/07-Diagrama de despliege-T2.png
  docs/images/07-Diagrama_de_despliege_T2.png
Labels: good first issue

#277 Sergio
  .github/workflows/asw2122.yml
  restapi/Dockerfile
  restapi/src/Api.ts
  restapi/src/Server.ts
  restapi/src/controllers/Product_Controller.ts
  restapi/src/entities/User.ts
  restapi/src/middlewares/Auth_Middleware.ts
  restapi/src/services/Product_Service.ts
  restapi/tests/api.test.ts
  webapp/Dockerfile
Labels: good first issue

#284 Centros de distribución y distancias con precio de envío
  data/data.py
  restapi/package-lock.json
  restapi/package.json
  restapi/src/Api.ts
  restapi/src/controllers/DistributionCenter_Controller.ts
  restapi/src/controllers/Order_Controller.ts
  restapi/src/controllers/ProductOrder_Controller.ts
  restapi/src/entities/DistributionCenter.ts
  restapi/src/entities/Order.ts
  restapi/src/entities/ProductInOrder.ts
  restapi/src/entities/ProductStore.ts
  restapi/src/services/DistributionCenter_Service.ts
  restapi/src/services/Order_Service.ts
  restapi/src/services/ProductOrder_Service.ts
  restapi/src/services/ProductStore_Service.ts
  restapi/src/services/Product_Service.ts
  restapi/src/services/User_Service.ts
Labels: BackEnd🧠

#285 Actualizar
  .github/workflows/asw2122.yml
  data/data.py
  docker-compose.yml
  package.json
  restapi/package-lock.json
  restapi/package.json
  restapi/src/Api.ts
  restapi/src/controllers/DistributionCenter_Controller.ts
  restapi/src/controllers/Order_Controller.ts
  restapi/src/controllers/ProductOrder_Controller.ts
  restapi/src/controllers/User_Controller.ts
  restapi/src/entities/DistributionCenter.ts
  restapi/src/entities/Order.ts
  restapi/src/entities/ProductInOrder.ts
  restapi/src/entities/ProductStore.ts
  restapi/src/services/DistributionCenter_Service.ts
  restapi/src/services/Order_Service.ts
  restapi/src/services/ProductOrder_Service.ts
  restapi/src/services/ProductStore_Service.ts
  restapi/src/services/Product_Service.ts
  restapi/src/services/User_Service.ts
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.tsx
  webapp/src/User.tsx
  webapp/src/api/api.ts
  webapp/src/components/Cart.tsx
  webapp/src/components/DisplayClients.tsx
  webapp/src/components/DisplayOrders.tsx
  webapp/src/components/Header.tsx
  webapp/src/components/Item.tsx
  webapp/src/index.tsx
  webapp/src/langs/en.json
  webapp/src/langs/es.json
  webapp/src/pages/Catalog.tsx
  webapp/src/pages/ClientView.tsx
  webapp/src/pages/CrudAddPage.tsx
  webapp/src/pages/CrudDeletePage.tsx
  webapp/src/pages/CrudEditPage.tsx
  webapp/src/pages/EditUserPage.tsx
  webapp/src/pages/HomePage.tsx
  webapp/src/pages/LoginPage.tsx
  webapp/src/pages/OrdersPage.tsx
  webapp/src/pages/ShippingPage.tsx
  webapp/src/pages/SignUpPage.tsx
  webapp/src/test/Header.test.tsx
Labels: BackEnd🧠

#288 Sergio
  .github/workflows/asw2122.yml
  .gitignore
  data/data.py
  restapi/src/middlewares/Auth_Middleware.ts
  restapi/tests/api.test.ts
  webapp/src/App.tsx
  webapp/src/api/api.ts
Labels: BackEnd🧠

#290 Añadida vista detalle básica, sticky header y botón GoToTop
  docker-compose.yml
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.tsx
  webapp/src/api/api.ts
  webapp/src/components/DisplayClients.tsx
  webapp/src/components/DisplayRelatedProducts.tsx
  webapp/src/components/Header.tsx
  webapp/src/components/ItemDetails.tsx
  webapp/src/components/RelatedProduct.tsx
  webapp/src/img/user-icon.svg
  webapp/src/img/user-list-icon.svg
  webapp/src/pages/Catalog.tsx
  webapp/src/pages/ClientView.tsx
  webapp/src/pages/EditUserPage.tsx
  webapp/src/pages/ProductDetailPage.tsx
  webapp/src/styles/Header.scss
Labels: FrontEnd👀

#295 Actualizar
  README.md
  docker-compose.yml
  webapp/package-lock.json
  webapp/package.json
  webapp/public/favicon.ico
  webapp/public/index.html
  webapp/public/logo-dede.ico
  webapp/src/App.tsx
  webapp/src/OpenCart.tsx
  webapp/src/api/api.ts
  webapp/src/components/Cart.tsx
  webapp/src/components/CartItem.tsx
  webapp/src/components/DisplayClients.tsx
  webapp/src/components/DisplayRelatedProducts.tsx
  webapp/src/components/HandleAddToCart.tsx
  webapp/src/components/HandleRemoveFromCart.tsx
  webapp/src/components/Header.tsx
  webapp/src/components/Item.tsx
  webapp/src/components/ItemDetails.tsx
  webapp/src/components/RelatedProduct.tsx
  webapp/src/img/logo-dede.svg
  webapp/src/img/user-icon.svg
  webapp/src/img/user-list-icon.svg
  webapp/src/index.tsx
  webapp/src/logo.svg
  webapp/src/pages/Catalog.tsx
  webapp/src/pages/ClientView.tsx
  webapp/src/pages/EditUserPage.tsx
  webapp/src/pages/LoginPage.tsx
  webapp/src/pages/OrdersPage.tsx
  webapp/src/pages/ProductDetailPage.tsx
  webapp/src/pages/ShippingPage.tsx
  webapp/src/pages/SignUpPage.tsx
  webapp/src/shared/shareddtypes.ts
  webapp/src/styles/Header.scss
  webapp/src/test/App.test.tsx
  webapp/src/test/Cart.test.tsx
  webapp/src/test/CatalogPage.test.tsx
  webapp/src/test/Header.test.tsx
  webapp/src/test/Item.test.tsx
  webapp/src/test/LogInPage.test.tsx
  webapp/src/test/OrderPage.test.tsx
  webapp/src/test/ShippingPage.test.tsx
  webapp/src/test/SignUpPage.test.tsx
Labels: BackEnd🧠

#303 Implementado limite de cantidad y añadido más stock
  data/data.py
  restapi/src/Api.ts
  restapi/src/controllers/ProductStore_Controller.ts
  restapi/src/services/ProductStore_Service.ts
Labels: BackEnd🧠

#305 Hot Fixs
  README.md
Labels: good first issue

#313 Funcionalidad de pedidos y centros de distribución (+ tests)
  data/data.py
  restapi/src/controllers/Order_Controller.ts
  restapi/src/controllers/Product_Controller.ts
  restapi/src/entities/Product.ts
  restapi/src/services/DistributionCenter_Service.ts
  restapi/src/services/ProductStore_Service.ts
  restapi/tests/api.test.ts
Labels: BackEnd🧠
