Repository Arquisoft/dede_es3c, pull requests merged in 2022-03, with the labels that each got.

#85 Actualización
  README.md
  README_es.md
  docs/01_introduction_and_goals.adoc
  docs/02_architecture_constraints.adoc
  docs/03_system_scope_and_context.adoc
  docs/04_solution_strategy.adoc
  docs/05_building_block_view.adoc
  docs/06_runtime_view.adoc
  docs/07_deployment_view.adoc
  docs/08_concepts.adoc
  docs/09_design_decisions.adoc
  docs/10_quality_scenarios.adoc
  docs/11_technical_risks.adoc
  docs/12_glossary.adoc
  docs/README.md
  docs/README_es.md
  docs/images/03-Business_Context.png
  docs/images/03-Technical-Context.png
  docs/images/05_1_Building_Block_View_Level_1.png
  docs/images/05_building_blocks-EN.png
  docs/images/07-DiagramaDespliege-T2.png
  docs/images/07-DiagramaDespliegue.png
  docs/images/08-Crosscutting-Concepts-Structure-EN.png
  docs/images/08_UI-Homepage.png
  docs/images/08_UI-OtherWindows.png
  docs/images/08_umldiagram.png
  docs/images/10_Quality-Requirements.png
  docs/images/UmlDiagram.png
  docs/index.adoc
Labels: documentation

#84 Areglado punto 10
  docs/10_quality_scenarios.adoc
Labels: documentation

#95 Arreglado 3.1 y 6.1
  docs/03_system_scope_and_context.adoc
  docs/06_runtime_view.adoc
  docs/10_quality_scenarios.adoc
  docs/images/03-Business_Context.png
Labels: documentation

#128 Implementado BackEnd
  .gitignore
  docker-compose.yml
  package-lock.json
  package.json
  restapi/Dockerfile
  restapi/ormconfig.json
  restapi/package-lock.json
  restapi/package.json
  restapi/src/Api.ts
  restapi/src/Config.ts
  restapi/src/Server.ts
  restapi/src/controllers/Product_Controller.ts
  restapi/src/controllers/User_Controller.ts
  restapi/src/data/data.py
  restapi/src/entities/Product.ts
  restapi/src/entities/User.ts
  restapi/src/middlewares/Auth_Middleware.ts
  restapi/src/persistence/Database.ts
  restapi/src/services/Product_Service.ts
  restapi/src/services/User_Service.ts
  restapi/tsconfig.json
  webapp/Dockerfile
Labels: Architecture, BackEnd

#140 Actualizar mi rama de trabajo
  docs/03_system_scope_and_context.adoc
  docs/06_runtime_view.adoc
  docs/10_quality_scenarios.adoc
  docs/images/03-Business_Context.png
  restapi/src/Server.ts
  restapi/src/middlewares/Auth_Middleware.ts
  restapi/src/persistence/Database.ts
Labels: BackEnd

#141 Implementación de los pedidos en el BackEnd
  .gitignore
  docker-compose.yml
  docs/03_system_scope_and_context.adoc
  docs/06_runtime_view.adoc
  docs/10_quality_scenarios.adoc
  docs/images/03-Business_Context.png
  package-lock.json
  package.json
  restapi/Dockerfile
  restapi/api.ts
  restapi/ormconfig.json
  restapi/package-lock.json
  restapi/package.json
  restapi/server.ts
  restapi/src/Api.ts
  restapi/src/Config.ts
  restapi/src/Server.ts
  restapi/src/controllers/Order_Controller.ts
  restapi/src/controllers/ProductOrder_Controller.ts
  restapi/src/controllers/Product_Controller.ts
  restapi/src/controllers/User_Controller.ts
  restapi/src/data/data.py
  restapi/src/entities/Order.ts
  restapi/src/entities/Product.ts
  restapi/src/entities/ProductInOrder.ts
  restapi/src/entities/User.ts
  restapi/src/middlewares/Auth_Middleware.ts
  restapi/src/persistence/Database.ts
  restapi/src/services/Order_Service.ts
  restapi/src/services/ProductOrder_Service.ts
  restapi/src/services/Product_Service.ts
  restapi/src/services/User_Service.ts
  restapi/tests/api.test.ts
  restapi/tsconfig.json
  webapp/Dockerfile
  webapp/package-lock.json
  webapp/package.json
Labels: BackEnd

#151 Actualizada documentación
  docs/12_hexagonal_architecture.adoc
  docs/13_glossary.adoc
  docs/images/logo-dede.png
  docs/index.adoc
Labels: documentation

#156 Añadido docker de python
  .gitignore
  data/.dockerignore
  data/Dockerfile
  data/README.md
  data/data.py
  data/requirements.txt
  docker-compose.yml
  restapi/src/middlewares/Auth_Middleware.ts
Labels: BackEnd

#157 Fix docker python
  data/data.py
  docker-compose.yml
Labels: BackEnd

#142 Mi parte del BackEnd añadida a Developer
  .gitignore
  docker-compose.yml
  docs/03_system_scope_and_context.adoc
  docs/06_runtime_view.adoc
  docs/10_quality_scenarios.adoc
  docs/images/03-Business_Context.png
  package-lock.json
  package.json
  restapi/Dockerfile
  restapi/api.ts
  restapi/ormconfig.json
  restapi/package-lock.json
  restapi/package.json
  restapi/server.ts
  restapi/src/Api.ts
  restapi/src/Config.ts
  restapi/src/Server.ts
  restapi/src/controllers/Order_Controller.ts
  restapi/src/controllers/ProductOrder_Controller.ts
  restapi/src/controllers/Product_Controller.ts
  restapi/src/controllers/User_Controller.ts
  restapi/src/data/data.py
  restapi/src/entities/Order.ts
  restapi/src/entities/Product.ts
  restapi/src/entities/ProductInOrder.ts
  restapi/src/entities/User.ts
  restapi/src/middlewares/Auth_Middleware.ts
  restapi/src/persistence/Database.ts
  restapi/src/services/Order_Service.ts
  restapi/src/services/ProductOrder_Service.ts
  restapi/src/services/Product_Service.ts
  restapi/src/services/User_Service.ts
  restapi/tests/api.test.ts
  restapi/tsconfig.json
  webapp/Dockerfile
  webapp/package-lock.json
  webapp/package.json
Labels: BackEnd

#160 todo el Backend
  .gitignore
  data/.dockerignore
  data/Dockerfile
  data/README.md
  data/data.py
  data/requirements.txt
  docker-compose.yml
  docs/01_introduction_and_goals.adoc
  docs/02_architecture_constraints.adoc
  docs/03_system_scope_and_context.adoc
  docs/06_runtime_view.adoc
  docs/09_design_decisions.adoc
  docs/10_quality_scenarios.adoc
  docs/11_technical_risks.adoc
  docs/12_hexagonal_architecture.adoc
  docs/13_glossary.adoc
  docs/images/03-Business_Context.png
  docs/images/logo-dede.png
  docs/index.adoc
  package-lock.json
  package.json
  restapi/Dockerfile
  restapi/api.ts
  restapi/ormconfig.json
  restapi/package-lock.json
  restapi/package.json
  restapi/server.ts
  restapi/src/Api.ts
  restapi/src/Config.ts
  restapi/src/Server.ts
  restapi/src/controllers/Order_Controller.ts
  restapi/src/controllers/ProductOrder_Controller.ts
  restapi/src/controllers/Product_Controller.ts
  restapi/src/controllers/User_Controller.ts
  restapi/src/entities/Order.ts
  restapi/src/entities/Product.ts
  restapi/src/entities/ProductInOrder.ts
  restapi/src/entities/User.ts
  restapi/src/middlewares/Auth_Middleware.ts
  restapi/src/persistence/Database.ts
  restapi/src/services/Order_Service.ts
  restapi/src/services/ProductOrder_Service.ts
  restapi/src/services/Product_Service.ts
  restapi/src/services/User_Service.ts
  restapi/tests/api.test.ts
  restapi/tsconfig.json
  webapp/Dockerfile
  webapp/package-lock.json
  webapp/package.json
Labels: BackEnd

#173 Developer
  docker-compose.yml
  restapi/src/Api.ts
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.tsx
  webapp/src/User.tsx
  webapp/src/api/api.ts
  webapp/src/components/DisplayProducts.tsx
  webapp/src/components/EmailForm.test.tsx
  webapp/src/components/EmailForm.tsx
  webapp/src/components/Header.tsx
  webapp/src/components/UserList.test.tsx
  webapp/src/components/UserList.tsx
  webapp/src/components/Welcome.test.tsx
  webapp/src/components/Welcome.tsx
  webapp/src/img/admin-conf-icon.svg
  webapp/src/img/catalog-icon.svg
  webapp/src/img/english-icon.svg
  webapp/src/img/home-icon.svg
  webapp/src/img/login-icon.svg
  webapp/src/img/logo-dede.svg
  webapp/src/img/logout-icon.svg
  webapp/src/img/register-icon.svg
  webapp/src/img/shopping-cart-icon.svg
  webapp/src/img/spanish-icon.svg
  webapp/src/index.tsx
  webapp/src/lang.tsx
  webapp/src/langs/en.json
  webapp/src/langs/es.json
  webapp/src/pages/Catalog.tsx
  webapp/src/pages/CrudAddPage.tsx
  webapp/src/pages/CrudDeletePage.tsx
  webapp/src/pages/CrudEditPage.tsx
  webapp/src/pages/HomePage.tsx
  webapp/src/pages/LoginPage.tsx
  webapp/src/pages/SignUpPage.tsx
  webapp/src/shared/shareddtypes.ts
Labels: FrontEnd, BackEnd

#174 Actualización de mi rama
  docker-compose.yml
  docs/01_introduction_and_goals.adoc
  docs/02_architecture_constraints.adoc
  docs/09_design_decisions.adoc
  docs/10_quality_scenarios.adoc
  docs/11_technical_risks.adoc
  docs/12_hexagonal_architecture.adoc
  docs/13_glossary.adoc
  docs/images/logo-dede.png
  docs/index.adoc
  restapi/src/Api.ts
  restapi/src/controllers/Order_Controller.ts
  restapi/src/controllers/ProductOrder_Controller.ts
  restapi/src/entities/Order.ts
  restapi/src/entities/ProductInOrder.ts
  restapi/src/services/Order_Service.ts
  restapi/src/services/ProductOrder_Service.ts
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.tsx
  webapp/src/User.tsx
  webapp/src/api/api.ts
  webapp/src/components/DisplayProducts.tsx
  webapp/src/components/EmailForm.test.tsx
  webapp/src/components/EmailForm.tsx
  webapp/src/components/Header.tsx
  webapp/src/components/UserList.test.tsx
  webapp/src/components/UserList.tsx
  webapp/src/components/Welcome.test.tsx
  webapp/src/components/Welcome.tsx
  webapp/src/img/admin-conf-icon.svg
  webapp/src/img/catalog-icon.svg
  webapp/src/img/english-icon.svg
  webapp/src/img/home-icon.svg
  webapp/src/img/login-icon.svg
  webapp/src/img/logo-dede.svg
  webapp/src/img/logout-icon.svg
  webapp/src/img/register-icon.svg
  webapp/src/img/shopping-cart-icon.svg
  webapp/src/img/spanish-icon.svg
  webapp/src/index.tsx
  webapp/src/lang.tsx
  webapp/src/langs/en.json
  webapp/src/langs/es.json
  webapp/src/pages/Catalog.tsx
  webapp/src/pages/CrudAddPage.tsx
  webapp/src/pages/CrudDeletePage.tsx
  webapp/src/pages/CrudEditPage.tsx
  webapp/src/pages/HomePage.tsx
  webapp/src/pages/LoginPage.tsx
  webapp/src/pages/SignUpPage.tsx
  webapp/src/shared/shareddtypes.ts
Labels: good first issue, FrontEnd, BackEnd

#175 actualización de mi rama
  docker-compose.yml
  webapp/src/App.tsx
  webapp/src/components/DisplayProducts.tsx
  webapp/src/components/Header.tsx
  webapp/src/langs/en.json
  webapp/src/langs/es.json
  webapp/src/pages/Catalog.tsx
  webapp/src/pages/CrudAddPage.tsx
  webapp/src/pages/CrudDeletePage.tsx
  webapp/src/pages/CrudEditPage.tsx
  webapp/src/pages/HomePage.tsx
  webapp/src/pages/LoginPage.tsx
  webapp/src/pages/SignUpPage.tsx
Labels: good first issue, FrontEnd, BackEnd

#199 Añadidas issues menores
  .gitignore
  data/data.py
  docker-compose.yml
  restapi/package-lock.json
  restapi/package.json
  restapi/src/Api.ts
  restapi/src/controllers/Product_Controller.ts
  restapi/src/controllers/User_Controller.ts
  restapi/src/entities/Product.ts
  restapi/src/entities/User.ts
  restapi/src/middlewares/Auth_Middleware.ts
  restapi/src/services/Product_Service.ts
Labels: BackEnd🧠

#209 Merge para unir frontend
  webapp/src/components/Cart.tsx
  webapp/src/components/CartItem.tsx
  webapp/src/components/Item.tsx
  webapp/src/pages/Catalog.tsx
  webapp/src/pages/CrudAddPage.tsx
  webapp/src/pages/CrudEditPage.tsx
  webapp/src/shared/shareddtypes.ts
Labels: FrontEnd👀
